DROP DATABASE p8db;
CREATE DATABASE p8db;
USE p8db;

DROP TABLE IF EXISTS users_teams;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS teams;

CREATE TABLE users(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  login VARCHAR(32) UNIQUE NOT NULL
) ENGINE=InnoDB;
CREATE TABLE teams(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(32) UNIQUE NOT NULL
) ENGINE=InnoDB;
CREATE TABLE users_teams(
  user_id INT UNSIGNED NOT NULL,
  team_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (team_id) REFERENCES teams(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB;

INSERT INTO users VALUES (DEFAULT , 'ivanov');
INSERT INTO teams VALUES (DEFAULT , 'teamA');
